### ISSUE TITLE
помоги

### ISSUE THREAD

**Issue by KROJIK** [IDriuk/lift#2]
подскажи,как сделать на 9 этажей ? 
я весь JS перекопал,и не нашел

**Comment by IDriuk** [comment]
- перерисовать схему лифта на 9 этажей ( сейчас 1, 2, 9, 19 и 20-й , надо 1, 2, 3, 4, 5, 6, 7, 8, 9-й);
- дальше найти в коде все , что относится к старым этажам (например ищи где встречается "19", где-то рядом будет то, что к остальным этажам относится, файлы data.js, display.js) и переделать по аналогии на новые;
- обратить внимание на крайние этажи, то есть 1-й делается аналогично 1-му, 9-й - 20-му, остальные одинаковые просто цифры будут меняться и настройки высоты (типа mechanic: [[240, 340], [], '', ''] ).
- еще надо будет понаходить все что относится к высоте, потому что лифт станет длинее (посмотреть стили, cab.js)
