### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by Dimasmsg** [IDriuk/lift#3]
помогите сделать еще этаж , буду очень рад если ответите

**Comment by IDriuk** [comment]
что именно не получается ? 
Изначально, возможность регулировать количество этажей где-нибудь в настройках не планировалась, поэтому простого способа добавить этаж нету. Наугад могу сказать, что надо перерисовать картинку схемы (найти в учебнике Манухина, добавить еще один этаж в какой-нибудь рисовальной программе ). Это еще до начала программирования. Потом найти все что касается этажа в коде (например 19-го) и сделать по аналогии 18-й. Потом понаходить и поменять общие параметры в коде и стилях, которые поменяются, например высота шахты лифта. 
Возможно вам не надо имитировать реальную электромеханическую схему. Если просто надо чтобы была некая кабина с дверями, которая ездит по этажам и открывает/закрывает двери, то имеет смысл использовать разные css классы для разных состояний, менять этим классы при onclick на кнопках и настроить свойство transition на нужное время, чтобы свойства классов менялись с анимацией и лифт как-бы ездил.
